### ISSUE TITLE
Link to docs page

### ISSUE THREAD

**Issue by xaur** [decred/dcrtimegui#106]
https://docs.decred.org/advanced/dcrtime/ has a nice write-up on how timestamping works.

**Comment by xaur** [comment]
Two places I would add this link to are this repo's About info and the README.

Alternatively, put https://timestamp.decred.org/ in About (it is common to put the well-known deploymend location in About), and both in README.

**Comment by tiagoalvesdulce** [comment]
Implemented in https://github.com/decred/dcrtimegui/pull/151
