### ISSUE TITLE
Show estimated time remaining

### ISSUE THREAD

**Issue by fulldecent** [decred/dcrtimegui#116]
On the waiting screen, e.g.

>https://timestamp.decred.org/results?digests=3375672f3e56a16aea36bf75dd565a7468ef54259d0cf8bbbb244d04a377c20c&names=2020Payroll23.csv&timestamp=true

it will be helpful to show an estimated time when the transaction could be complete.

**Comment by tiagoalvesdulce** [comment]
Implemented in https://github.com/decred/dcrtimegui/pull/151

**Comment by fulldecent** [comment]
Awesome, thank you, great stuff here
