### ISSUE TITLE
Add JSON API

### ISSUE THREAD

**Issue by fulldecent** [decred/dcrtimegui#117]
# Specification

Create new route:

```
POST https://timestamp.decred.org/api/stamp
```

which accepts like:

```json
[
   "11779c9e577ee238a61dc49227bc8cd8cbd7f8db60efb7d2d3336706d32b5372",
   "fc11cc406688eb75d83ee3db77f4d1776b81de16ddba10738a7d3703299b7646",
   "000000000000000000000000000000000000000000000000000000000000000a"
]
```

and also like

```
GET https://timestamp.decred.org/api/stamp?digests=11779c9e577ee238a61dc49227bc8cd8cbd7f8db60efb7d2d3336706d32b5372,fc11cc406688eb75d83ee3db77f4d1776b81de16ddba10738a7d3703299b7646,000000000000000000000000000000000000000000000000000000000000000a
```

and produces like:

```javascript
[
   {
      "digest": "000e63e5a6f9b5cc6c2ab40b60b51604c9116517ccd6b42a8461d4fe66ee3e80",
      "servertimestamp": 1544810400,
      "chaininformation": {
         "chaintimestamp": 1544007625,
         "transaction": "bcbf33effd142a5f048d94b6c470f43a5d8b7c052c6d357ddb797ce26aab2842",
         "merkleroot": "f3f4a2a803d1fdf974a5abdb9208c5a4680b1805f53c6d38cadfba632f52e9cc",
         "merklepath": [
            "234250c8a63f951068f8aa398858566c",
            "1a1940411310586824c139f968c6d90c",
            "dfd65ad4d8575c92c5a21e072bd158c8",
            "de8e9ce8bba50a5d2390cd8f898b0ae4",
            "2387a971a3271478f1dab154b638f5e1",
            "1186925126d002915fd588c94927c864",
            "0901914d0e2c0abd86ff48e2cdbce9b2",
            "5b225d6a762bb9587e2ea7a270a350c0",
            "5181b7248ba10af037fe37dd84b98bd7"
         ],
      }
   },
   {
      "digest": "fc11cc406688eb75d83ee3db77f4d1776b81de16ddba10738a7d3703299b7646",
      "servertimestamp": 1544810400,
      "submittedjustnow": false // SERVER SAW THIS BEFORE, IT IS "PENDING"
      "chaininformation": null, // THIS IS REDUNDANT BUT ADDED TO MAKE API FRIENDLIER
      "estimatedcompletiontime": 1544810500 // WHEN WE EXPECT RUNNING THIS API AGAIN WILL PRODUCE chaininformation NOT NULL
   },
   {
      "digest": "000000000000000000000000000000000000000000000000000000000000000a",
      "servertimestamp": 1544808400,
      "submittedjustnow": true, // THIS WAS NEVER SEEN BEFORE, ADDED TO QUEUE
      "chaininformation": null, // THIS IS REDUNDANT BUT ADDED TO MAKE API FRIENDLIER
      "estimatedcompletiontime": 1544810500 // WHEN WE EXPECT RUNNING THIS API AGAIN WILL PRODUCE chaininformation NOT NULL
   }
]
```

Then link from like https://timestamp.decred.org/results?digests=3375672f3e56a16aea36bf75dd565a7468ef54259d0cf8bbbb244d04a377c20c&names=2020Payroll23.csv&timestamp=true to this new page.

Also link from https://timestamp.decred.org/ directly to this GitHub issue as documentation. Improve "later".

# Discussion

This will help people think about making their application integrate with Decred. And that's something we want.

P.S. Later, I'd like to see extended output that shows some more useful information e.g. Merkel inclusion proof that the transaction is in the block and then a few sets of Merkel proofs showing this block is inside the subsequent block... continuing until some number of blocks where that block is timestamped on Bitcoin blockchain, and that inclusion proof. This produces a high degree of confidence and may be accepted by the type of government auditors I am working with.

P.P.S. Also, I'd like to see a separate route like `GET /api/verify` which produces the above "more useful information" when sent a "chaininformation" from above. This will allow `dcrtimegui` to still be useful even when it is not storing every hash and proof in its O(n) permanent database.

P.P.P.S. Then actually switch `dcrtimegui` to a O(1) database. This will improve consumer confidence that this service can be supported long-term and that it won't disappear because it ran out of funding for the infinite database expense.

Thank you for your consideration.

**Comment by tiagoalvesdulce** [comment]
We already have https://github.com/decred/dcrtime. To use the API:

**Mainnet**
https://time.decred.org:49152

**Testnet**
https://time-testnet.decred.org:59152

There's also a Javascript wrapper: https://github.com/tiagoalvesdulce/dcrtimejs

**Comment by davecgh** [comment]
I think it's https://timestamp.decred.org:49152 instead of just time

**Comment by fulldecent** [comment]
Awesome, thank you!
