### ISSUE TITLE
Show human readable timestamp

### ISSUE THREAD

**Issue by xaur** [decred/dcrtimegui#144]
I came to check the digest posted [here](https://haddadoficial.com.br/lula-e-haddad-registram-plano-de-governo-em-blockchain-para-evitar-fake-news/) and it worked, but it shows a Unix timestamp `1666375959`. Humans coming from that page would not understand when the document was time-stamped, while the point in *time* when content was anchored is the key use case of dcrtime.

It would be nice to show `2022-10-21 18:12:39` along the Unix timestamp.

**Comment by tiagoalvesdulce** [comment]
Implemented in https://github.com/decred/dcrtimegui/pull/151
