### ISSUE TITLE
Make transaction ID clickable and link to dcrdata

### ISSUE THREAD

**Issue by xaur** [decred/dcrtimegui#145]
If I input a hash to check, the Results page currently shows

> Transaction: 21a5c0b90ae27db69b21700fcbb9365116ba2f0d40351a217a22c1593b013188

It would be nice to have this tx hash clickable and linking to https://dcrdata.decred.org/tx/21a5c0b90ae27db69b21700fcbb9365116ba2f0d40351a217a22c1593b013188

**Comment by tiagoalvesdulce** [comment]
Implemented in https://github.com/decred/dcrtimegui/pull/151
