### ISSUE TITLE
Format hashes input

### ISSUE THREAD

**Issue by victorgcramos** [decred/dcrtimegui#146]
The "Search for hashes" input tells users that it accepts multiple hashes. However, if users type hashes with blank spaces,
the form will redirect to `https://timestamp.decred.org/results#hashes=<hash-1>,%20<hash-2>`, which throws a JSON parse error and enters on an infinite loading state, as described below:

```
Unhandled Promise Rejection: SyntaxError: JSON Parse error: Unexpected identifier "Invalid"
```
<img width="1068" alt="Screen Shot 2022-11-23 at 6 03 01 PM" src="https://user-images.githubusercontent.com/22639213/203645587-5f83e4e5-66fc-43b8-b391-89938a07c346.png">

I think we should format these inputs (or validate them), so users don't get redirected to a loading page.

**Comment by tiagoalvesdulce** [comment]
this behavior will be changed in the redesign

**Comment by tiagoalvesdulce** [comment]
Not needed after https://github.com/decred/dcrtimegui/pull/151
