### ISSUE TITLE
Add page to pretty display twitter threads based on a IPFS cid

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/dcrtimegui#65]
We need a page such as `timestamp.decred.org/timestampbot/threads/<ipfs_cid>` where we validate that the provided `ipfs_cid` leads to a valid thread and pretty display that thread in a twiter(ish) style. We may also include the timestamping status of that thread.

**Comment by tiagoalvesdulce** [comment]
Closing it because the timestamp bot now have its own frontend

**Comment by xaur** [comment]
Source code behind https://twitter.com/dcrtimestampbot is now at https://github.com/JC60522/dcr_timestampbot

**Comment by xaur** [comment]
In case anyone wants to migrate this feature request to the new repo, it looks like the new version is not storing threads at all, or it is not showing them. Documented it all in https://github.com/JC60522/dcr_timestampbot/issues/2
