### ISSUE TITLE
Dcrtime UI/UX improvements

### ISSUE THREAD

**Issue by harlovski** [decred/dcrtimegui#67]
Added second flow with direct input hash, added search bar. Improved results page and main page. 

Below you can find redesigned pages:
Preview: https://xd.adobe.com/view/9cefbc0a-08ac-482d-5f2a-5df75ec591e7-eade/
Specs:  https://xd.adobe.com/spec/2af300cc-83cf-4951-5fc8-85f2e3d389e3-5cc2/
Zip with all icons and "not found" illustration: [Timestamp assets.zip](https://github.com/decred/dcrtimegui/files/3138652/Timestamp.assets.zip)

**Comment by amassarwi** [comment]
@fernandoabolafio 
Nice improvements, would like to join you working on it

**Comment by amassarwi** [comment]
@fernandoabolafio  I would suggest we align the modal to other parts of the website and show `{title} icon` and not the other way - see screenshot below, what do you think ?

![image](https://user-images.githubusercontent.com/10324528/63881370-fbb70680-c9cf-11e9-8188-aa41365692a5.png)

**Comment by thi4go** [comment]
Hey @harlovski. I'm currently implementing the redesign on dcrtimegui, and noticed that there is a missing modal from the specs, the one referent to the `Digest` field in result card. Other than that, everything is running smooth. :+1:

**Comment by harlovski** [comment]
> Hey @harlovski. I'm currently implementing the redesign on dcrtimegui, and noticed that there is a missing modal from the specs, the one referent to the `Digest` field in result card. Other than that, everything is running smooth. 👍

Hi. I can't understand, what are you talking about, sorry :D
We don't have modals. We have just one card on homepage, where you can drop file or input hash, then you go to the results page.
Can you explain again, what do you mean? 
![image](https://user-images.githubusercontent.com/47418864/68112901-8b62bf00-ff03-11e9-9d19-390157b51348.png)

**Comment by thi4go** [comment]
Hey mate, from your screenshots, seems like I was looking at an old spec. Could you send the correct url please?

**Comment by harlovski** [comment]
https://xd.adobe.com/spec/1ddc2090-7f31-4ae1-7ace-81747448c37c-6bed/

**Comment by harlovski** [comment]
![image](https://user-images.githubusercontent.com/47418864/68119568-18157900-ff14-11e9-84f1-17ca4576d404.png)
Maybe this?
It opens when we click on the information icon next to the title "Create new digest"

**Comment by tiagoalvesdulce** [comment]
@harlovski Can you share the XD file as well?
