### ISSUE TITLE
handleProcessFiles linter warning

### ISSUE THREAD

**Issue by dajohi** [decred/dcrtimegui#69]
`
src/pages/Results.js
  59:9  warning  The 'handleProcessFiles' function makes the dependencies of useEffect Hook (at line 57) change on every render.  Move it inside the useEffect callback. Alternatively, wrap the 'handleProcessFiles' definition into its own useCallback() Hook  react-hooks/exhaustive-deps
`

**Comment by fernandoabolafio** [comment]
Closed on https://github.com/decred/dcrtimegui/pull/71
